blog/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :articles
=begin
  	GET "/articles" index
  	POST "/articles" create
  	DELETE "/articles/:id" destroy
  	GET "/articles/:id" show
  	GET "/articles/new" new
  	GET "/articles/:id/edit" edit
  	PATCH "/articles/:id" update
  	PUT "/articles/:id" update
=end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'articles#index'
end

blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog/app/models/article.rb
class Article < ApplicationRecord
	validates :title, presence: true, uniqueness: true
	validates :body, presence: true, length: {minimum: 20}
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	#before_filter :find_model
	#private
	#def find_model
	#	@model = Articles.find(params[:id]) if params[:id]
	#end
	#GET /articles/
	def index
		@articles = Article.all
	end

	#GET /articles/:id
	def show
		@article = Article.find(params[:id])
	end

	#GET /articles/new
	def new
		@article = Article.new
	end

	#GET /articles/create
	def create
		@article = Article.new(article_params)
		if @article.save
			redirect_to @article
		else
			render :new
		end
	end

	#DELETE /articles/:id
	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to articles_path
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		if @article.update(article_params)
			redirect_to @article
		else
			render :edit
		end
	end

	private
	def article_params
		params.require(:article).permit(:title,:body)
	end
end

blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog/app/views/articles/_form.html.erb
<% name ||= "Ingresar" %>
<h1><%=name%> un Artículo</h1>
<div style="width:80%;margin:0px auto">
<%= form_for(@article) do |a| %>
	<% @article.errors.full_messages.each do |message| %>
		<div>*<%=message%></div>
	<% end %>
	<div><%= a.text_field :title, placeholder:"Título", class:"form-control"%></div>
	<div><%= a.text_area :body, placeholder:"Cuerpo del Artículo", class:"form-control"%></div>
	<div><%= a.submit "Guardar", style:"background-color:#C61732;	color:#fff;	padding:10px 5px;"%></div>
<%end%>
</div>

blog/app/views/articles/edit.html.erb
<%= render "form", name: "Editar" %>

blog/app/views/articles/index.html.erb
<% @articles.each do |article| %>
	<h1><%= link_to article.title, article %></h1>
	<div><%= article.body %></div> - <%=  link_to "Eliminar", article, style:"color:#C61732 !important", method: :delete %>
<%end%>
<%=resp%>

blog/app/views/articles/new.html.erb
<%= render "form" %>

blog/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<div><%= @article.body %></div>
<div><%= link_to "Editar", edit_article_path(@article) %></div>
<div><%= link_to "Volver", articles_path %></div>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  	<header>
  		<nav id="menu">
  			<ul>
  				<li class="item">Blog Facilito</li>
  				<li class="item"><%= link_to "Inicio",root_path %></li>
  				<li class="item">Diseño</li>
  				<li class="item">Programación</li>
  				<li class="item">Tegnología</li>
  			</ul>
  		</nav>
  	</header>
    <%= yield %>
  </body>
</html>

blog/app/views/welcome/index.html.erb
<h1>¡Bienvenido a este Blog</h1>

<% [10,50,25,26].each do |numero|%>
<p>Número : <%=numero%></p>
<%end%>